name: Latest blog post workflow
on:
  schedule:
    - cron: '5 4 * * sun'
    workflow_dispatch:
        input:
            tags:
                description: 'Tags to label this manual run (optional)'
                default: 'Manual run'
jobs:
  update-readme-with-blog:
    name: To update this README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "https://ktafakkori.github.io/feed.xml"
          template: "$newline - $emojiKey(🤖,⚡,🔥,🦾,📢) [$title]($url?utm_source=github&utm_medium=profile&utm_campaign=github-readme)"